legged_hil_hw:
  loop_frequency: 1000
  cycle_time_error_threshold: 0.002
  kp: 50.0
  kd: 40.0

  lcm_cpu_list: ""
  wbc_cpu_list: "" 
  mpc_cpu_list: ""
  lcm_thread_priority: 80
  wbc_thread_priority: 95
  mpc_thread_priority: 50